import type { Static, TSchema } from "@sinclair/typebox";
import type { Action, ActionErrorDefinition } from "./types";
import { ActionExecutionError, ValidationError } from "./types";

/**
 * Eden/tRPC-style typed HTTP client inferred from Brick-TS application contracts.
 *
 * The frontend imports only the contract *type* — never a backend implementation:
 *
 * ```ts
 * import { createBrickClient } from "@brickkit/core/client";
 * import type { AppServer } from "./server"; // `import type`: erased at build
 *
 * const api = createBrickClient<AppServer>({ baseUrl: "http://localhost:4000" });
 * const pages = await api.page.list({ limit: 10, sort: "-createdAt" });
 * const created = await api.page.create({ title: "Hello", content: "World" });
 * ```
 *
 * Build the contract from individually-typed actions (each `defineAction` call
 * preserves its input/output/error literal types):
 *
 * ```ts
 * // server.ts (backend)
 * export const listPages = pagesService.action({ name: "page.list", ... });
 * export const createPage = pagesService.action({ name: "page.create", ... });
 * export const contract = { page: { list: listPages, create: createPage } };
 * export type AppServer = typeof contract;
 * ```
 *
 * ## Result / error convention
 *
 * The client uses a throw-based convention that mirrors local `action.execute`
 * semantics, because TypeScript promises cannot encode thrown exception types:
 *
 * - Success → the promise resolves with the action output.
 * - Declared domain failures (your `errors: { SLUG_EXISTS: ... }`) and framework
 *   guards (UNAUTHORIZED/FORBIDDEN/NOT_FOUND/...) → rejected with
 *   {@link ActionExecutionError} carrying the declared `code`, `status`,
 *   `message`, and `details`. Narrow with `instanceof` and read `err.code`.
 * - Input/output validation failures → rejected with {@link ValidationError},
 *   exactly as local execution throws.
 * - Network failures, unparsable bodies, and non-OK responses outside the
 *   declared contract → {@link BrickTransportError} (4xx) or
 *   {@link BrickServerError} (5xx).
 * - Cancellation via `AbortSignal` → the native `AbortError` propagates
 *   unwrapped so `err.name === "AbortError"` keeps working.
 *
 * ## URL mapping
 *
 * A client path is a namespace walk ending in an action call. The leaf segment
 * decides the route, matching the server compiler (`packages/cli/src/compiler`):
 *
 * | Client call | HTTP request |
 * |---|---|
 * Generated browser contracts carry each action's HTTP method and path,
 * including plugin routes and consumer overrides. Without runtime metadata,
 * callers use `POST /api/<service>/<action>` with dotted action names.
 * GET/DELETE input is serialized as a query string; other methods send JSON.

 */

export interface BrickClientOptions {
  /** Server origin, e.g. `"http://localhost:4000"`. No trailing slash required. */
  baseUrl: string;
  /**
   * Route prefix the server was mounted with (default `"/api"`).
   * Must match the `prefix` passed to `brick({ prefix })`.
   */
  prefix?: string;
  /**
   * Default headers sent with every call (e.g. an `Authorization` bearer).
   * A thunk is re-evaluated per call, so rotated tokens stay fresh.
   */
  headers?:
    | Record<string, string>
    | (() => Record<string, string> | Promise<Record<string, string>>);
  /** `fetch` implementation. Defaults to `globalThis.fetch`. */
  fetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
  /** Default signal applied to every call (per-call `signal` wins). */
  signal?: AbortSignal;
  /** Default per-call timeout in milliseconds (per-call `timeoutMs` wins). */
  timeoutMs?: number;
  /**
   * Browser-safe route metadata generated by the Brick Vite plugin.
   * Required for custom methods/paths and plugin routes. Without a contract,
   * calls use POST and service/action names inferred from namespace keys.
   */
  contract?: Record<string, any>;
}

/** Browser-safe action metadata generated by the Brick Vite plugin. */
export interface BrickClientAction<
  TInput = unknown,
  TOutput = unknown,
  TErrors = {},
> {
  kind: "action";
  name: string;
  serviceName: string;
  config: { path: string; method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" };
  /** Type information only; never emitted at runtime. */
  readonly __types?: { input: TInput; output: TOutput; errors: TErrors };
}

export interface BrickCallOptions {
  /** Extra headers merged over the client defaults for this call only. */
  headers?: Record<string, string>;
  /** Abort signal for this call only. Never wrapped: aborts reject with `AbortError`. */
  signal?: AbortSignal;
  /** Per-call timeout in milliseconds. Implemented with `AbortSignal.timeout`. */
  timeoutMs?: number;
}

/**
 * The request never received a meaningful server answer: DNS / connection
 * failure, a malformed body, or a 4xx response outside the declared contract
 * (no `code` and no `ValidationError` shape).
 */
export class BrickTransportError extends Error {
  readonly kind = "transport" as const;
  readonly status?: number;
  readonly url: string;
  readonly body?: unknown;
  override readonly cause?: unknown;

  constructor(
    message: string,
    opts: { status?: number; url: string; body?: unknown; cause?: unknown },
  ) {
    super(message);
    this.name = "BrickTransportError";
    this.status = opts.status;
    this.url = opts.url;
    this.body = opts.body;
    this.cause = opts.cause;
  }
}

/**
 * The server answered 5xx without a declared `code` / `ValidationError` shape,
 * i.e. an unexpected failure rather than a modelled domain error.
 */
export class BrickServerError extends Error {
  readonly kind = "server" as const;
  readonly status: number;
  readonly url: string;
  readonly body: unknown;

  constructor(
    message: string,
    opts: { status: number; url: string; body: unknown },
  ) {
    super(message);
    this.name = "BrickServerError";
    this.status = opts.status;
    this.url = opts.url;
    this.body = opts.body;
  }
}

export function isBrickTransportError(
  err: unknown,
): err is BrickTransportError {
  return err instanceof BrickTransportError;
}

export function isBrickServerError(err: unknown): err is BrickServerError {
  return err instanceof BrickServerError;
}

/** Static input type from the schema, with a fallback for structural actions. */
export type InferActionInput<A> =
  A extends BrickClientAction<infer I, any, any>
    ? I
    : A extends {
          config: { input?: infer S extends TSchema };
        }
      ? Static<S>
      : A extends {
            execute(params: { input?: infer I; ctx?: any }): any;
          }
        ? I
        : A extends { run(input?: infer I, ctx?: any): any }
          ? I
          : A extends (params: { input?: infer I; ctx?: any }) => any
            ? I
            : unknown;

/** Resolved output type of an action. */
export type InferActionOutput<A> =
  A extends BrickClientAction<any, infer O, any>
    ? O
    : A extends (...args: any[]) => Promise<infer O>
      ? O
      : A extends { execute(params: any): Promise<infer O> }
        ? O
        : unknown;

/** Union of error `code`s declared in an action's `errors` map. */
export type InferActionErrorCodes<A> =
  A extends BrickClientAction<any, any, infer E>
    ? Extract<keyof E, string>
    : A extends {
          config: { errors?: infer E };
        }
      ? E extends Record<string, ActionErrorDefinition>
        ? Extract<keyof E, string>
        : never
      : never;

/**
 * The declared failure shape of an action for `catch` narrowing:
 * ```ts
 * try { await api.page.create(input); }
 * catch (err) {
 *   if (err instanceof ActionExecutionError) {
 *     const code: InferActionErrorCodes<typeof createPage> | "UNAUTHORIZED" | ... = err.code;
 *   }
 * }
 * ```
 * (Standard framework codes are always possible alongside declared ones.)
 */
export type InferActionFailure<A> = ActionExecutionError & {
  code:
    | InferActionErrorCodes<A>
    | "BAD_REQUEST"
    | "UNAUTHORIZED"
    | "FORBIDDEN"
    | "NOT_FOUND"
    | "CONFLICT"
    | "INTERNAL_SERVER_ERROR"
    | "VALIDATION_ERROR";
};

/**
 * Typed caller for one action. Required inputs stay required; actions whose
 * input includes `undefined` (no schema / all-optional) can be called bare.
 */
export type BrickActionCaller<A> =
  undefined extends InferActionInput<A>
    ? (
        input?: InferActionInput<A>,
        options?: BrickCallOptions,
      ) => Promise<InferActionOutput<A>>
    : (
        input: InferActionInput<A>,
        options?: BrickCallOptions,
      ) => Promise<InferActionOutput<A>>;

/** Recursively maps action leaves and their namespaces to browser callers. */
export type BrickClient<T> = T extends
  | BrickClientAction<any, any, any>
  | Action<any, any, any, any>
  ? BrickActionCaller<T>
  : T extends (...args: any[]) => any
    ? BrickActionCaller<T>
    : T extends object
      ? { [K in keyof T]: BrickClient<T[K]> }
      : T;

interface ResolvedClientOptions {
  baseUrl: string;
  prefix: string;
  headers?: BrickClientOptions["headers"];
  fetch: NonNullable<BrickClientOptions["fetch"]>;
  signal?: AbortSignal;
  timeoutMs?: number;
}

function normalizeBaseUrl(baseUrl: string): string {
  const trimmed = baseUrl.replace(/\/+$/, "");
  if (!trimmed)
    throw new Error("[Brick-TS client] `baseUrl` must not be empty.");
  return trimmed;
}

function normalizePrefix(prefix: string | undefined): string {
  if (!prefix) return "/api";
  const withLeading = prefix.startsWith("/") ? prefix : `/${prefix}`;
  return withLeading.length > 1 ? withLeading.replace(/\/+$/, "") : withLeading;
}

function toQueryString(input: unknown): string {
  if (input == null || typeof input !== "object") return "";
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(input as Record<string, unknown>)) {
    if (value === undefined || value === null) continue;
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item === undefined || item === null) continue;
        params.append(
          key,
          typeof item === "object" ? JSON.stringify(item) : String(item),
        );
      }
    } else if (typeof value === "object") {
      params.append(key, JSON.stringify(value));
    } else {
      params.append(key, String(value));
    }
  }
  const qs = params.toString();
  return qs ? `?${qs}` : "";
}

interface PlannedRequest {
  method: string;
  url: string;
  body: unknown;
  hasBody: boolean;
}

function isActionValue(value: unknown): value is {
  serviceName?: unknown;
  name?: unknown;
  config: Action<any, any, any, any>["config"];
} & Function {
  return (
    typeof value === "function" &&
    !!(value as any).config &&
    typeof (value as any).config.execute === "function"
  );
}

function isClientAction(value: unknown): value is BrickClientAction {
  return (
    !!value &&
    typeof value === "object" &&
    (value as BrickClientAction).kind === "action"
  );
}

function planRequest(
  path: string[],
  /** Runtime contract value at `path`, when the `contract` option is set. */
  target: unknown,
  input: unknown,
  baseUrl: string,
  prefix: string,
): PlannedRequest {
  if (path.length === 0) {
    throw new Error(
      "[Brick-TS client] No action selected: call a leaf such as `api.page.list(input)`.",
    );
  }
  const actionTarget =
    isActionValue(target) || isClientAction(target) ? target : undefined;
  const actionConfig = actionTarget?.config;
  if (path.length < 2) {
    throw new Error(
      `[Brick-TS client] Cannot address '${path.join(".")}': custom actions need a service segment, e.g. \`api.${path[0]}.<action>(input)\`.`,
    );
  }
  // Exact mode: the runtime contract reveals the bound service/action names,
  // so contract keys can differ from backend names.
  const service =
    typeof actionTarget?.serviceName === "string" && actionTarget.serviceName
      ? actionTarget.serviceName
      : path[0]!;
  const action =
    typeof actionTarget?.name === "string" && actionTarget.name
      ? actionTarget.name
      : path.slice(1).join(".");
  const method = actionConfig?.method ?? "POST";
  const configuredPath = actionConfig?.path;
  let actionPath =
    configuredPath ??
    `${prefix}/${encodeURIComponent(service)}/${action.split(".").map(encodeURIComponent).join(".")}`;
  let remaining = input;
  if (configuredPath !== undefined) {
    if (!configuredPath.startsWith("/")) {
      throw new Error("[Brick-TS client] Action paths must start with '/'.");
    }
    const source = { ...((input ?? {}) as Record<string, unknown>) };
    const record = { ...source };
    actionPath = actionPath.replace(/:([^/]+)/g, (_match, key: string) => {
      const value = Object.hasOwn(source, key) ? source[key] : undefined;
      if (value === undefined || value === null || value === "") {
        throw new Error(`[Brick-TS client] Missing path parameter '${key}'.`);
      }
      delete record[key];
      return encodeURIComponent(String(value));
    });
    remaining = input === undefined ? undefined : record;
  }
  const queryOnly = method === "GET" || method === "DELETE";
  return {
    method,
    url: `${baseUrl}${actionPath}${queryOnly ? toQueryString(remaining) : ""}`,
    body: queryOnly ? undefined : remaining,
    hasBody: !queryOnly && remaining !== undefined,
  };
}

function toActionError(status: number, body: unknown, url: string): Error {
  if (body !== null && typeof body === "object") {
    const record = body as Record<string, unknown>;
    if (typeof record.code === "string") {
      return new ActionExecutionError(
        record.code,
        typeof record.message === "string" ? record.message : record.code,
        typeof record.status === "number" ? record.status : status,
        (record.details ?? undefined) as unknown,
      );
    }
    if (record.name === "ValidationError") {
      return new ValidationError(
        typeof record.message === "string"
          ? record.message
          : "Validation failed",
        Array.isArray(record.errors) ? (record.errors as any) : [],
        typeof record.status === "number" ? record.status : status,
      );
    }
  }
  if (status >= 500) {
    return new BrickServerError(
      `Unexpected server error (status ${status}) for ${url}.`,
      {
        status,
        url,
        body,
      },
    );
  }
  return new BrickTransportError(
    `Request failed with status ${status} for ${url}.`,
    {
      status,
      url,
      body,
    },
  );
}

async function dispatch(
  resolved: ResolvedClientOptions,
  path: string[],
  target: unknown,
  input: unknown,
  callOptions: BrickCallOptions | undefined,
): Promise<unknown> {
  const { method, url, body, hasBody } = planRequest(
    path,
    target,
    input,
    resolved.baseUrl,
    resolved.prefix,
  );

  const staticHeaders =
    typeof resolved.headers === "function"
      ? await resolved.headers()
      : (resolved.headers ?? {});
  const headers: Record<string, string> = {
    accept: "application/json",
    ...staticHeaders,
    ...callOptions?.headers,
  };
  let payload: string | undefined;
  if (hasBody) {
    headers["content-type"] = "application/json";
    payload = JSON.stringify(body ?? null);
  }

  const timeoutMs = callOptions?.timeoutMs ?? resolved.timeoutMs;
  let timeoutSignal: AbortSignal | undefined;
  if (timeoutMs !== undefined) timeoutSignal = AbortSignal.timeout(timeoutMs);
  const signal = callOptions?.signal ?? timeoutSignal ?? resolved.signal;

  let response: Response;
  try {
    response = await resolved.fetch(url, {
      method,
      headers,
      body: payload,
      signal,
    });
  } catch (err) {
    if (err instanceof Error && err.name === "AbortError") throw err;
    throw new BrickTransportError(
      `Network request failed for ${url}: ${err instanceof Error ? err.message : String(err)}`,
      { url, cause: err },
    );
  }

  let parsed: unknown;
  const text = await response.text();
  if (response.headers.get("content-type")?.includes("text/plain")) {
    parsed = text;
  } else if (text) {
    try {
      parsed = JSON.parse(text);
    } catch (err) {
      if (!response.headers.has("content-type")) {
        parsed = text;
      } else {
        throw new BrickTransportError(`Unparsable response body for ${url}.`, {
          status: response.status,
          url,
          cause: err,
        });
      }
    }
  }

  if (response.ok) return parsed;
  throw toActionError(response.status, parsed, url);
}

function childNode(node: unknown, prop: string): unknown {
  if (
    node != null &&
    (typeof node === "object" || typeof node === "function")
  ) {
    return (node as Record<string, unknown>)[prop];
  }
  return undefined;
}

function createNamespace(
  resolved: ResolvedClientOptions,
  path: string[],
  node: unknown,
): any {
  const callable = async (input?: unknown, options?: BrickCallOptions) =>
    dispatch(resolved, path, node, input, options);
  return new Proxy(callable, {
    get(target, prop, receiver) {
      if (typeof prop !== "string") return Reflect.get(target, prop, receiver);
      // Never masquerade as a thenable: awaiting a namespace must not dispatch.
      if (prop === "then" || prop === "catch" || prop === "finally")
        return undefined;
      return createNamespace(resolved, [...path, prop], childNode(node, prop));
    },
    apply(_target, _thisArg, args: unknown[]) {
      const [input, options] = args as [unknown, BrickCallOptions | undefined];
      return dispatch(resolved, path, node, input, options);
    },
  });
}

/**
 * Create an Eden/tRPC-style typed client for the application contract `TApp`.
 * `TApp` is a type-only parameter: `import type { AppServer }` keeps backend
 * implementations out of the frontend bundle.
 */
export function createBrickClient<TApp extends Record<string, any>>(
  options: BrickClientOptions & { contract: TApp },
): BrickClient<TApp>;
export function createBrickClient<TApp extends Record<string, any>>(
  options: BrickClientOptions,
): BrickClient<TApp>;
export function createBrickClient<TApp extends Record<string, any>>(
  options: BrickClientOptions,
): BrickClient<TApp> {
  if (!options?.baseUrl)
    throw new Error(
      '[Brick-TS client] `baseUrl` is required, e.g. `{ baseUrl: "http://localhost:4000" }`.',
    );
  const fetchImpl = options.fetch ?? globalThis.fetch;
  if (typeof fetchImpl !== "function") {
    throw new Error(
      "[Brick-TS client] No `fetch` implementation available: pass `fetch` explicitly.",
    );
  }
  const resolved: ResolvedClientOptions = {
    baseUrl: normalizeBaseUrl(options.baseUrl),
    prefix: normalizePrefix(options.prefix),
    headers: options.headers,
    fetch: fetchImpl,
    signal: options.signal,
    timeoutMs: options.timeoutMs,
  };
  return createNamespace(resolved, [], options.contract) as BrickClient<TApp>;
}
