import { join } from "node:path";

// Post-process `bun run db:schema` output: point the generated schema at the
// single drizzle-orm copy backing `@brickkit/core/pg`. The CLI emits
// `drizzle-orm` / `drizzle-orm/pg-core` imports, which resolve to whichever
// workspace copy the loader finds, while the framework runtime
// (defineDatabase, drizzleAdapter) uses core's copy; mixing the two breaks
// table-type identity (brand symbols) at typecheck and runtime.
//
// The rewrite parses whatever names the CLI emitted and re-emits one sorted
// import, so new builders in future CLI output keep working as long as
// `packages/core/src/db/pg.ts` re-exports them.
const path = join(import.meta.dir, "../src/api/auth/schema.ts");
const generated = await Bun.file(path).text();

const headerPattern =
  /import \{([^}]*)\} from "drizzle-orm";\nimport \{([^}]*)\} from "drizzle-orm\/pg-core";/;
const match = generated.match(headerPattern);
if (!match) {
  console.log(
    "schema imports already point at @brickkit/core/pg; nothing to do",
  );
  process.exit(0);
}
const names = `${match[1]},${match[2]}`
  .split(",")
  .map((name) => name.trim())
  .filter(Boolean)
  .sort();
const rewritten = generated.replace(
  headerPattern,
  `import { ${names.join(", ")} } from "@brickkit/core/pg";`,
);

// The CLI occasionally emits a bare `.default()` (no value) that this
// drizzle-orm version rejects at typecheck; it means "no default", so drop it.
const normalized = rewritten.replace(/\.default\(\),/g, ",");
const header = `// GENERATED by \`bun run db:schema\` (better-auth CLI). Do not edit by hand;\n// re-run the script instead. Excluded from oxlint (generated key order).\n`;
const output = normalized.startsWith("// GENERATED")
  ? normalized
  : header + normalized;
await Bun.write(path, output);
console.log("schema imports pointed at @brickkit/core/pg");
