import { createHash } from "node:crypto";
import { getPluginActionRoute, type Service } from "@brickkit/core";
import type { BrickClientAction } from "@brickkit/core/client";
import type { BrickApp } from "./endpoints";

/** Generate browser metadata and transport types from the app's selected services. */
export function generateClientContract(app: BrickApp): string {
  const { services, prefix } = app.definition;
  const contract: Record<string, any> = Object.create(null);
  const types: Record<string, any> = Object.create(null);
  const resourceActions = new Set<unknown>();
  const schemas = new SchemaTypes();
  for (const service of services) {
    addResources(service, prefix, contract, types, resourceActions, schemas);
  }
  for (const service of services) {
    addServiceActions(
      service,
      prefix,
      contract,
      types,
      resourceActions,
      schemas,
    );
  }
  return `// Generated by the Brick Vite plugin. Do not edit.
import type { BrickClientAction } from "@brickkit/core/client";

${schemas.renderContract(namespaceType(types))}

export const contract: AppContract = JSON.parse(${JSON.stringify(JSON.stringify(contract))});
`;
}

function addResources(
  service: Service<any, any>,
  prefix: string,
  contract: Record<string, any>,
  types: Record<string, any>,
  resourceActions: Set<unknown>,
  schemas: SchemaTypes,
) {
  for (const resource of service.listResources()) {
    if (Object.hasOwn(contract, resource.name))
      throw new Error(`Brick client: duplicate namespace '${resource.name}'`);
    const node: Record<string, any> = Object.create(null);
    const typeNode: Record<string, any> = Object.create(null);
    contract[resource.name] = node;
    types[resource.name] = typeNode;
    const enabled = new Set(service.listActions());
    for (const [operation, method, item] of [
      ["list", "GET", false],
      ["create", "POST", false],
      ["get", "GET", true],
      ["update", "PATCH", true],
      ["delete", "DELETE", true],
    ] as const) {
      const action = resource.actions[operation];
      resourceActions.add(action);
      if (!enabled.has(action)) continue;
      const itemPath = item ? `/:${resource.idField}` : "";
      const path = `${prefix}/${resource.name}${itemPath}`;
      node[operation] = {
        kind: "action",
        name: action.name,
        serviceName: service.name,
        config: { path, method },
      };
      const inputType = schemas.generate(action.config.input);
      // The runtime list result always includes these metadata fields.
      const outputSchema =
        operation === "list"
          ? {
              ...action.config.output,
              required: [
                ...new Set([
                  ...(action.config.output?.required ?? []),
                  "items",
                  "total",
                  "limit",
                  "offset",
                  "pageCount",
                  "hasMore",
                  "nextCursor",
                ]),
              ],
            }
          : action.config.output;
      typeNode[operation] = actionType(
        inputType,
        schemas.generate(outputSchema),
        action.config.errors,
      );
    }
  }
}

function addServiceActions(
  service: Service<any, any>,
  prefix: string,
  contract: Record<string, any>,
  types: Record<string, any>,
  resourceActions: Set<unknown>,
  schemas: SchemaTypes,
) {
  const namespace: Record<string, any> =
    contract[service.name] ?? Object.create(null);
  const namespaceTypes: Record<string, any> =
    types[service.name] ?? Object.create(null);
  contract[service.name] = namespace;
  types[service.name] = namespaceTypes;
  for (const action of service.listActions()) {
    if (resourceActions.has(action)) continue;
    const pluginRoute = getPluginActionRoute(action, prefix);
    if (pluginRoute === false) continue;
    const { input, output, errors, path, method } = action.config;
    let inputType: string;
    let outputType: string;
    try {
      inputType = input ? schemas.generate(input) : "unknown";
      outputType = output ? schemas.generate(output) : "unknown";
    } catch (error) {
      throw new Error(
        `Brick client: cannot generate '${service.name}.${action.name}': ${(error as Error).message}`,
      );
    }
    const metadata: BrickClientAction = {
      kind: "action",
      name: action.name,
      serviceName: service.name,
      config: {
        path:
          pluginRoute?.path ??
          path ??
          `${prefix}/${service.name}/${action.name}`,
        method: pluginRoute?.method ?? method ?? "POST",
      },
    };
    insertAction(
      pluginRoute?.clientPath ? contract : namespace,
      pluginRoute?.clientPath ? types : namespaceTypes,
      metadata,
      actionType(inputType, outputType, errors),
      pluginRoute?.clientPath,
    );
  }
}

function insertAction(
  node: Record<string, any>,
  typeNode: Record<string, any>,
  metadata: BrickClientAction,
  type: string,
  clientPath?: readonly string[],
) {
  const segments = clientPath ?? metadata.name.split(".");
  for (const segment of segments.slice(0, -1)) {
    if (
      Object.hasOwn(typeNode, segment) &&
      typeof typeNode[segment] === "string"
    ) {
      throw new Error(
        `Brick client: action namespace collision at '${metadata.serviceName}.${metadata.name}'`,
      );
    }
    node[segment] ??= Object.create(null);
    typeNode[segment] ??= Object.create(null);
    node = node[segment];
    typeNode = typeNode[segment];
  }
  const leaf = segments.at(-1)!;
  if (Object.hasOwn(node, leaf))
    throw new Error(
      `Brick client: action namespace collision at '${metadata.serviceName}.${metadata.name}'`,
    );
  node[leaf] = metadata;
  typeNode[leaf] = type;
}

function actionType(
  input: string,
  output: string,
  errors: Record<string, unknown> | undefined,
): string {
  const codes = Object.keys(errors ?? {});
  const errorsType = codes.length
    ? `Record<${codes.map((code) => JSON.stringify(code)).join(" | ")}, { message: string; status?: number }>`
    : "{}";
  return `BrickClientAction<${input}, ${output}, ${errorsType}>`;
}

function namespaceType(node: Record<string, any>): string {
  return `{\n${Object.entries(node)
    .map(
      ([key, value]) =>
        `  ${JSON.stringify(key)}: ${typeof value === "string" ? value : namespaceType(value)};`,
    )
    .join("\n")}\n}`;
}

// Emit transport types from schemas, rather than importing backend callbacks or databases.
class SchemaTypes {
  private readonly aliases = new Map<string, string>();
  private readonly names = new Set([
    "AppContract",
    "BrickClientAction",
    "contract",
  ]);

  // Internal tokens cannot occur in JSON-escaped property names or literals.
  private readonly fragments: { body: string; size: number; hash: string }[] =
    [];
  private readonly fragmentIds = new Map<string, number>();

  private fragment(body: string): string {
    let id = this.fragmentIds.get(body);
    if (id === undefined) {
      id = this.fragments.length;
      const size =
        body.replace(/\0(\d+)\0/g, "").length +
        [...body.matchAll(/\0(\d+)\0/g)].reduce(
          (total, match) => total + this.fragments[Number(match[1])]!.size,
          0,
        );
      const shape = body.replace(
        /\0(\d+)\0/g,
        (_, child) => this.fragments[Number(child)]!.hash,
      );
      const hash = createHash("sha256").update(shape).digest("hex");
      this.fragments.push({ body, size, hash });
      this.fragmentIds.set(body, id);
    }
    return `\0${id}\0`;
  }

  renderContract(contract: string): string {
    const uses = this.fragments.map(() => 0);
    const count = (body: string, multiplier: number) => {
      for (const match of body.matchAll(/\0(\d+)\0/g))
        uses[Number(match[1])]! += multiplier;
    };
    count(contract, 1);
    for (const body of this.aliases.values()) count(body, 1);
    const shared = new Map<number, string>();
    // Parents are interned after their children. Once a parent is shared, its
    // children occur only once in its declaration, avoiding overlapping savings.
    for (let id = this.fragments.length - 1; id >= 0; id--) {
      const { body, size, hash } = this.fragments[id]!;
      const nameBase = `BrickSchema_${hash.slice(0, 12)}`;
      let name = nameBase;
      let suffix = 2;
      while (this.names.has(name)) name = `${nameBase}_${suffix++}`;
      const declarationCost = `export type ${name} = ;\n\n`.length;
      if (
        uses[id]! > 1 &&
        (uses[id]! - 1) * size > uses[id]! * name.length + declarationCost
      ) {
        this.names.add(name);
        shared.set(id, name);
      }
      count(body, shared.has(id) ? 1 : uses[id]!);
    }
    const rendered: string[] = [];
    const declarations: string[] = [];
    for (let id = 0; id < this.fragments.length; id++) {
      const body = this.fragments[id]!.body.replace(
        /\0(\d+)\0/g,
        (_, child) => rendered[Number(child)]!,
      );
      const name = shared.get(id);
      // Child aliases can make a parent too small to justify sharing it.
      if (
        name &&
        (uses[id]! - 1) * body.length >
          uses[id]! * name.length + `export type ${name} = ;\n\n`.length
      ) {
        declarations.push(`export type ${name} = ${body};\n\n`);
        rendered.push(name);
      } else rendered.push(body);
    }
    const render = (body: string) =>
      body.replace(/\0(\d+)\0/g, (_, id) => rendered[Number(id)]!);
    return (
      declarations.join("") +
      [...this.aliases]
        .map(([name, type]) => `export type ${name} = ${render(type)};\n\n`)
        .join("") +
      `export type AppContract = ${render(contract)};`
    );
  }

  generate(root: any): string {
    // IDs belong to this schema document. Separate actions may reuse the same ID.
    const ids = new Map<string, any>();
    const references: { ref: string; base: any }[] = [];
    const resources = new Map<unknown, any>();
    const active = new Set<unknown>();
    const visit = (schema: any, base: any) => {
      if (!schema || typeof schema !== "object" || active.has(schema)) return;
      const currentBase =
        typeof schema.$id === "string" && schema.$id ? schema : base;
      if (!resources.has(schema)) resources.set(schema, currentBase);
      if (typeof schema.$ref === "string")
        references.push({ ref: schema.$ref, base: currentBase });
      active.add(schema);
      try {
        if (typeof schema.$id === "string" && schema.$id)
          ids.set(schema.$id, schema);
        for (const key of [
          "properties",
          "patternProperties",
          "$defs",
          "definitions",
        ]) {
          for (const child of Object.values(schema[key] ?? {}))
            visit(child, currentBase);
        }
        for (const key of ["anyOf", "oneOf", "allOf", "prefixItems"]) {
          for (const child of schema[key] ?? []) visit(child, currentBase);
        }
        for (const key of ["items", "additionalProperties", "not"]) {
          if (Array.isArray(schema[key]))
            schema[key].forEach((child: any) => visit(child, currentBase));
          else visit(schema[key], currentBase);
        }
      } finally {
        active.delete(schema);
      }
    };
    visit(root, root);

    const resolve = (reference: string, base: any): any => {
      const hashIndex = reference.indexOf("#");
      const id = hashIndex === -1 ? reference : reference.slice(0, hashIndex);
      const fragment =
        hashIndex === -1 ? undefined : reference.slice(hashIndex + 1);
      let target = id ? ids.get(id) : base;
      if (fragment) {
        if (!fragment.startsWith("/")) return undefined;
        try {
          for (const part of decodeURIComponent(fragment).slice(1).split("/")) {
            const key = part.replaceAll("~1", "/").replaceAll("~0", "~");
            if (!target || !Object.hasOwn(target, key)) return undefined;
            target = target[key];
          }
        } catch {
          return undefined;
        }
      }
      return typeof target === "boolean" ||
        (target && typeof target === "object")
        ? target
        : undefined;
    };
    const targets = new Set(
      references
        .map(({ ref, base }) => resolve(ref, base))
        .filter((value) => value !== undefined),
    );
    const names = new Map<any, string>();
    const emit = (schema: any, inline = false, base: any = root): string => {
      const body = emitInline(schema, inline, base);
      // References already have document-scoped aliases; scalars stay inline.
      if (
        schema &&
        !schema.$ref &&
        !Object.hasOwn(schema, "const") &&
        (schema.anyOf ||
          schema.oneOf ||
          schema.allOf ||
          schema.enum?.length > 1 ||
          schema.type === "array" ||
          schema.type === "object")
      )
        return this.fragment(body);
      return body;
    };
    const emitInline = (schema: any, inline: boolean, base: any): string => {
      if (schema === undefined || schema === true) return "unknown";
      if (schema === false || (schema.not && !Object.keys(schema.not).length))
        return "never";
      const currentBase =
        schema &&
        typeof schema === "object" &&
        typeof schema.$id === "string" &&
        schema.$id
          ? schema
          : base;
      if (!inline && targets.has(schema)) {
        const existing = names.get(schema);
        if (existing) return existing;
        // Titles provide readable names; generated TypeBox IDs remain usable fallbacks.
        const hint = schema.title ?? schema.$id ?? "Schema";
        let nameBase = String(hint).replace(/[^a-zA-Z0-9_$]/g, "_");
        if (!/^[a-zA-Z_$]/.test(nameBase)) nameBase = `Schema_${nameBase}`;
        nameBase = `Brick${nameBase}`;
        let name = nameBase;
        let suffix = 2;
        while (this.names.has(name)) {
          name = `${nameBase}_${suffix}`;
          suffix += 1;
        }
        this.names.add(name);
        names.set(schema, name);
        // names is reserved before the body is rendered, so recursive refs terminate.
        this.aliases.set(name, emit(schema, true, currentBase));
        return name;
      }
      if (schema.$ref) {
        const target = resolve(schema.$ref, currentBase);
        if (target === undefined)
          throw new Error(`unresolved schema reference '${schema.$ref}'`);
        const targetBase =
          target && typeof target === "object"
            ? (resources.get(target) ?? root)
            : currentBase;
        return emit(target, false, targetBase);
      }
      if (Object.hasOwn(schema, "const")) return JSON.stringify(schema.const);
      if (schema.enum)
        return (
          schema.enum
            .map((value: unknown) => JSON.stringify(value))
            .join(" | ") || "never"
        );
      if (schema.anyOf || schema.oneOf)
        return `(${(schema.anyOf ?? schema.oneOf).map((child: any) => emit(child, false, currentBase)).join(" | ")})`;
      if (schema.allOf)
        return `(${schema.allOf.map((child: any) => emit(child, false, currentBase)).join(" & ")})`;
      switch (schema.type) {
        case "string":
          return "string";
        case "number":
        case "integer":
          return "number";
        case "boolean":
          return "boolean";
        case "null":
          return "null";
        case "undefined":
        case "void":
          return "undefined";
        case "array":
          if (Array.isArray(schema.items))
            return `[${schema.items.map((child: any) => emit(child, false, currentBase)).join(", ")}]`;
          return `Array<${emit(schema.items, false, currentBase)}>`;
        case "object": {
          const entries = Object.entries(schema.properties ?? {});
          const properties = entries.map(
            ([key, value]) =>
              `${JSON.stringify(key)}${schema.required?.includes(key) ? "" : "?"}: ${emit(value, false, currentBase)};`,
          );
          // additionalProperties applies to keys matched by neither properties
          // nor patternProperties, so union it instead of discarding it.
          const indexParts = Object.values(schema.patternProperties ?? {}).map(
            (child) => emit(child, false, currentBase),
          );
          if (schema.additionalProperties) {
            indexParts.push(
              emit(schema.additionalProperties, false, currentBase),
            );
          }
          let indexType: string | undefined;
          if (indexParts.length) {
            // TS index signatures must also cover declared keys, so widen
            // with their types; otherwise the intersection below rejects
            // valid values. Over-approximating is safe: the server validates.
            for (const [, value] of entries) {
              const propType = emit(value, false, currentBase);
              if (!indexParts.includes(propType)) indexParts.push(propType);
            }
            indexType = indexParts.join(" | ");
          }
          const object = `{ ${properties.join(" ")} }`;
          if (indexType) {
            const index = `{ [key: string]: ${indexType} }`;
            return properties.length ? `${object} & ${index}` : index;
          }
          return object;
        }
        case undefined:
          return "unknown";
        default:
          throw new Error(`unsupported transport schema type '${schema.type}'`);
      }
    };
    return emit(root);
  }
}
