import type { Service } from "@brickkit/core";
import type { BrickClientAction } from "@brickkit/core/client";
import type { BrickApp } from "./endpoints";

/** Generate browser metadata and transport types from the app's selected services. */
export function generateClientContract(app: BrickApp): string {
  const { services, prefix } = app.definition;
  const contract: Record<string, any> = Object.create(null);
  const types: Record<string, any> = Object.create(null);
  const resourceActions = new Set<unknown>();
  const schemas = new SchemaTypes();
  for (const service of services) {
    addResources(service, prefix, contract, types, resourceActions, schemas);
  }
  for (const service of services) {
    addServiceActions(
      service,
      prefix,
      contract,
      types,
      resourceActions,
      schemas,
    );
  }
  return `// Generated by the Brick Vite plugin. Do not edit.
import type { BrickClientAction } from "@brickkit/core/client";

${schemas.declarations()}export type AppContract = ${namespaceType(types)};

export const contract: AppContract = JSON.parse(${JSON.stringify(JSON.stringify(contract))});
`;
}

function addResources(
  service: Service<any, any>,
  prefix: string,
  contract: Record<string, any>,
  types: Record<string, any>,
  resourceActions: Set<unknown>,
  schemas: SchemaTypes,
) {
  for (const resource of service.listResources()) {
    if (Object.hasOwn(contract, resource.name))
      throw new Error(`Brick client: duplicate namespace '${resource.name}'`);
    const node: Record<string, any> = Object.create(null);
    const typeNode: Record<string, any> = Object.create(null);
    contract[resource.name] = node;
    types[resource.name] = typeNode;
    const enabled = new Set(service.listActions());
    for (const [operation, method, item] of [
      ["list", "GET", false],
      ["create", "POST", false],
      ["get", "GET", true],
      ["update", "PATCH", true],
      ["delete", "DELETE", true],
    ] as const) {
      const action = resource.actions[operation];
      resourceActions.add(action);
      if (!enabled.has(action)) continue;
      const itemPath = item ? `/:${resource.idField}` : "";
      const path = `${prefix}/${resource.name}${itemPath}`;
      node[operation] = {
        kind: "action",
        name: action.name,
        serviceName: service.name,
        config: { path, method },
      };
      const inputType = schemas.generate(action.config.input);
      // The runtime list result always includes these metadata fields.
      const outputSchema =
        operation === "list"
          ? {
              ...action.config.output,
              required: [
                ...new Set([
                  ...(action.config.output?.required ?? []),
                  "items",
                  "total",
                  "limit",
                  "offset",
                  "pageCount",
                  "hasMore",
                  "nextCursor",
                ]),
              ],
            }
          : action.config.output;
      typeNode[operation] = actionType(
        inputType,
        schemas.generate(outputSchema),
        action.config.errors,
      );
    }
  }
}

function addServiceActions(
  service: Service<any, any>,
  prefix: string,
  contract: Record<string, any>,
  types: Record<string, any>,
  resourceActions: Set<unknown>,
  schemas: SchemaTypes,
) {
  const namespace: Record<string, any> =
    contract[service.name] ?? Object.create(null);
  const namespaceTypes: Record<string, any> =
    types[service.name] ?? Object.create(null);
  contract[service.name] = namespace;
  types[service.name] = namespaceTypes;
  for (const action of service.listActions()) {
    if (resourceActions.has(action)) continue;
    const { input, output, errors, path, method } = action.config;
    let inputType: string;
    let outputType: string;
    try {
      inputType = input ? schemas.generate(input) : "unknown";
      outputType = output ? schemas.generate(output) : "unknown";
    } catch (error) {
      throw new Error(
        `Brick client: cannot generate '${service.name}.${action.name}': ${(error as Error).message}`,
      );
    }
    const metadata: BrickClientAction = {
      kind: "action",
      name: action.name,
      serviceName: service.name,
      config: {
        path: path ?? `${prefix}/${service.name}/${action.name}`,
        method: method ?? "POST",
      },
    };
    insertAction(
      namespace,
      namespaceTypes,
      metadata,
      actionType(inputType, outputType, errors),
    );
  }
}

function insertAction(
  node: Record<string, any>,
  typeNode: Record<string, any>,
  metadata: BrickClientAction,
  type: string,
) {
  const segments = metadata.name.split(".");
  for (const segment of segments.slice(0, -1)) {
    if (
      Object.hasOwn(typeNode, segment) &&
      typeof typeNode[segment] === "string"
    ) {
      throw new Error(
        `Brick client: action namespace collision at '${metadata.serviceName}.${metadata.name}'`,
      );
    }
    node[segment] ??= Object.create(null);
    typeNode[segment] ??= Object.create(null);
    node = node[segment];
    typeNode = typeNode[segment];
  }
  const leaf = segments.at(-1)!;
  if (Object.hasOwn(node, leaf))
    throw new Error(
      `Brick client: action namespace collision at '${metadata.serviceName}.${metadata.name}'`,
    );
  node[leaf] = metadata;
  typeNode[leaf] = type;
}

function actionType(
  input: string,
  output: string,
  errors: Record<string, unknown> | undefined,
): string {
  const codes = Object.keys(errors ?? {});
  const errorsType = codes.length
    ? `Record<${codes.map((code) => JSON.stringify(code)).join(" | ")}, { message: string; status?: number }>`
    : "{}";
  return `BrickClientAction<${input}, ${output}, ${errorsType}>`;
}

function namespaceType(node: Record<string, any>): string {
  return `{\n${Object.entries(node)
    .map(
      ([key, value]) =>
        `  ${JSON.stringify(key)}: ${typeof value === "string" ? value : namespaceType(value)};`,
    )
    .join("\n")}\n}`;
}

// Emit transport types from schemas, rather than importing backend callbacks or databases.
class SchemaTypes {
  private aliases = new Map<string, string>();
  private names = new Set(["AppContract", "BrickClientAction", "contract"]);

  declarations(): string {
    return [...this.aliases]
      .map(([name, type]) => `export type ${name} = ${type};\n\n`)
      .join("");
  }

  generate(root: any): string {
    // IDs belong to this schema document. Separate actions may reuse the same ID.
    const ids = new Map<string, any>();
    const references: string[] = [];
    const visited = new Set<unknown>();
    const visit = (schema: any) => {
      if (!schema || typeof schema !== "object" || visited.has(schema)) return;
      visited.add(schema);
      if (schema.$id) ids.set(schema.$id, schema);
      if (schema.$ref) references.push(schema.$ref);
      for (const key of [
        "properties",
        "patternProperties",
        "$defs",
        "definitions",
      ]) {
        for (const child of Object.values(schema[key] ?? {})) visit(child);
      }
      for (const key of ["anyOf", "oneOf", "allOf", "prefixItems"]) {
        for (const child of schema[key] ?? []) visit(child);
      }
      for (const key of ["items", "additionalProperties", "not"]) {
        if (Array.isArray(schema[key])) schema[key].forEach(visit);
        else visit(schema[key]);
      }
    };
    visit(root);

    const resolve = (reference: string): any => {
      const [id, fragment] = reference.split("#");
      let target = id ? ids.get(id) : root;
      if (fragment) {
        if (!fragment.startsWith("/")) return undefined;
        try {
          for (const part of decodeURIComponent(fragment).slice(1).split("/")) {
            const key = part.replace(/~1/g, "/").replace(/~0/g, "~");
            if (!target || !Object.hasOwn(target, key)) return undefined;
            target = target[key];
          }
        } catch {
          return undefined;
        }
      }
      return typeof target === "boolean" ||
        (target && typeof target === "object")
        ? target
        : undefined;
    };
    const targets = new Set(
      references.map(resolve).filter((value) => value !== undefined),
    );
    const names = new Map<any, string>();
    const emit = (schema: any, inline = false): string => {
      if (schema === undefined || schema === true) return "unknown";
      if (schema === false || (schema.not && !Object.keys(schema.not).length))
        return "never";
      if (!inline && targets.has(schema)) {
        const existing = names.get(schema);
        if (existing) return existing;
        // Titles provide readable names; generated TypeBox IDs remain usable fallbacks.
        const hint = schema.title ?? schema.$id ?? "Schema";
        let base = String(hint).replace(/[^a-zA-Z0-9_$]/g, "_");
        if (!/^[a-zA-Z_$]/.test(base)) base = `Schema_${base}`;
        base = `Brick${base}`;
        let name = base;
        for (let suffix = 2; this.names.has(name); suffix++)
          name = `${base}_${suffix}`;
        this.names.add(name);
        names.set(schema, name);
        // Reserve the alias before its body is rendered, so recursive refs terminate.
        this.aliases.set(name, "");
        this.aliases.set(name, emit(schema, true));
        return name;
      }
      if (schema.$ref) {
        const target = resolve(schema.$ref);
        if (target === undefined)
          throw new Error(`unresolved schema reference '${schema.$ref}'`);
        return emit(target);
      }
      if (Object.hasOwn(schema, "const")) return JSON.stringify(schema.const);
      if (schema.enum)
        return (
          schema.enum
            .map((value: unknown) => JSON.stringify(value))
            .join(" | ") || "never"
        );
      if (schema.anyOf || schema.oneOf)
        return `(${(schema.anyOf ?? schema.oneOf).map((child: any) => emit(child)).join(" | ")})`;
      if (schema.allOf)
        return `(${schema.allOf.map((child: any) => emit(child)).join(" & ")})`;
      switch (schema.type) {
        case "string":
          return "string";
        case "number":
        case "integer":
          return "number";
        case "boolean":
          return "boolean";
        case "null":
          return "null";
        case "undefined":
        case "void":
          return "undefined";
        case "array":
          if (Array.isArray(schema.items))
            return `[${schema.items.map((child: any) => emit(child)).join(", ")}]`;
          return `Array<${emit(schema.items)}>`;
        case "object": {
          const properties = Object.entries(schema.properties ?? {}).map(
            ([key, value]) =>
              `${JSON.stringify(key)}${schema.required?.includes(key) ? "" : "?"}: ${emit(value)};`,
          );
          const patterns = Object.values(schema.patternProperties ?? {});
          const indexType = patterns.length
            ? patterns.map((child) => emit(child)).join(" | ")
            : schema.additionalProperties
              ? emit(schema.additionalProperties)
              : undefined;
          const object = `{ ${properties.join(" ")} }`;
          if (indexType) {
            const index = `{ [key: string]: ${indexType} }`;
            return properties.length ? `${object} & ${index}` : index;
          }
          return object;
        }
        case undefined:
          return "unknown";
        default:
          throw new Error(`unsupported transport schema type '${schema.type}'`);
      }
    };
    return emit(root);
  }
}
