import type { Service } from "@brickkit/core";
import type { BrickClientAction } from "@brickkit/core/client";
import type { BrickApp } from "./endpoints";

/** Generate browser metadata and transport types from the app's selected services. */
export function generateClientContract(app: BrickApp): string {
  const { services, prefix } = app.definition;
  const contract: Record<string, any> = Object.create(null);
  const types: Record<string, any> = Object.create(null);
  const resourceActions = new Set<unknown>();
  for (const service of services) {
    addResources(service, prefix, contract, types, resourceActions);
  }
  for (const service of services) {
    addServiceActions(service, prefix, contract, types, resourceActions);
  }
  return `// Generated by the Brick Vite plugin. Do not edit.
import type { BrickClientAction } from "@brickkit/core/client";

export type AppContract = ${namespaceType(types)};

export const contract: AppContract = JSON.parse(${JSON.stringify(JSON.stringify(contract))});
`;
}

function addResources(
  service: Service<any, any>,
  prefix: string,
  contract: Record<string, any>,
  types: Record<string, any>,
  resourceActions: Set<unknown>,
) {
  for (const resource of service.listResources()) {
    if (Object.hasOwn(contract, resource.name))
      throw new Error(`Brick client: duplicate namespace '${resource.name}'`);
    const node: Record<string, any> = Object.create(null);
    const typeNode: Record<string, any> = Object.create(null);
    contract[resource.name] = node;
    types[resource.name] = typeNode;
    const enabled = new Set(service.listActions());
    for (const [operation, method, item] of [
      ["list", "GET", false],
      ["create", "POST", false],
      ["get", "GET", true],
      ["update", "PATCH", true],
      ["delete", "DELETE", true],
    ] as const) {
      const action = resource.actions[operation];
      resourceActions.add(action);
      if (!enabled.has(action)) continue;
      const itemPath = item ? `/:${resource.idField}` : "";
      const path = `${prefix}/${resource.name}${itemPath}`;
      node[operation] = {
        kind: "action",
        name: action.name,
        serviceName: service.name,
        config: { path, method },
      };
      const inputType = schemaType(action.config.input);
      // The runtime list result always includes these metadata fields.
      const outputSchema =
        operation === "list"
          ? {
              ...action.config.output,
              required: [
                ...new Set([
                  ...(action.config.output?.required ?? []),
                  "items",
                  "total",
                  "limit",
                  "offset",
                  "pageCount",
                  "hasMore",
                  "nextCursor",
                ]),
              ],
            }
          : action.config.output;
      typeNode[operation] = actionType(
        inputType,
        schemaType(outputSchema),
        action.config.errors,
      );
    }
  }
}

function addServiceActions(
  service: Service<any, any>,
  prefix: string,
  contract: Record<string, any>,
  types: Record<string, any>,
  resourceActions: Set<unknown>,
) {
  const namespace: Record<string, any> =
    contract[service.name] ?? Object.create(null);
  const namespaceTypes: Record<string, any> =
    types[service.name] ?? Object.create(null);
  contract[service.name] = namespace;
  types[service.name] = namespaceTypes;
  for (const action of service.listActions()) {
    if (resourceActions.has(action)) continue;
    const { input, output, errors, path, method } = action.config;
    let inputType: string;
    let outputType: string;
    try {
      inputType = input ? schemaType(input) : "unknown";
      outputType = output ? schemaType(output) : "unknown";
    } catch (error) {
      throw new Error(
        `Brick client: cannot generate '${service.name}.${action.name}': ${(error as Error).message}`,
      );
    }
    const metadata: BrickClientAction = {
      kind: "action",
      name: action.name,
      serviceName: service.name,
      config: {
        path: path ?? `${prefix}/${service.name}/${action.name}`,
        method: method ?? "POST",
      },
    };
    insertAction(
      namespace,
      namespaceTypes,
      metadata,
      actionType(inputType, outputType, errors),
    );
  }
}

function insertAction(
  node: Record<string, any>,
  typeNode: Record<string, any>,
  metadata: BrickClientAction,
  type: string,
) {
  const segments = metadata.name.split(".");
  for (const segment of segments.slice(0, -1)) {
    if (
      Object.hasOwn(typeNode, segment) &&
      typeof typeNode[segment] === "string"
    ) {
      throw new Error(
        `Brick client: action namespace collision at '${metadata.serviceName}.${metadata.name}'`,
      );
    }
    node[segment] ??= Object.create(null);
    typeNode[segment] ??= Object.create(null);
    node = node[segment];
    typeNode = typeNode[segment];
  }
  const leaf = segments.at(-1)!;
  if (Object.hasOwn(node, leaf))
    throw new Error(
      `Brick client: action namespace collision at '${metadata.serviceName}.${metadata.name}'`,
    );
  node[leaf] = metadata;
  typeNode[leaf] = type;
}

function actionType(
  input: string,
  output: string,
  errors: Record<string, unknown> | undefined,
): string {
  const codes = Object.keys(errors ?? {});
  const errorsType = codes.length
    ? `Record<${codes.map((code) => JSON.stringify(code)).join(" | ")}, { message: string; status?: number }>`
    : "{}";
  return `BrickClientAction<${input}, ${output}, ${errorsType}>`;
}

function namespaceType(node: Record<string, any>): string {
  return `{\n${Object.entries(node)
    .map(
      ([key, value]) =>
        `  ${JSON.stringify(key)}: ${typeof value === "string" ? value : namespaceType(value)};`,
    )
    .join("\n")}\n}`;
}

// Emit transport types from schemas, rather than importing backend callbacks or databases.
function schemaType(schema: any): string {
  if (schema === undefined) return "unknown";
  if (schema === true) return "unknown";
  if (schema === false || (schema.not && !Object.keys(schema.not).length))
    return "never";
  if (schema.$ref)
    throw new Error(`unresolved schema reference '${schema.$ref}'`);
  if (Object.hasOwn(schema, "const")) return JSON.stringify(schema.const);
  if (schema.enum)
    return (
      schema.enum.map((value: unknown) => JSON.stringify(value)).join(" | ") ||
      "never"
    );
  if (schema.anyOf || schema.oneOf)
    return `(${(schema.anyOf ?? schema.oneOf).map(schemaType).join(" | ")})`;
  if (schema.allOf) return `(${schema.allOf.map(schemaType).join(" & ")})`;
  switch (schema.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "undefined":
    case "void":
      return "undefined";
    case "array":
      return arraySchemaType(schema);
    case "object":
      return objectSchemaType(schema);
    case undefined:
      return "unknown";
    default:
      throw new Error(`unsupported transport schema type '${schema.type}'`);
  }
}

function arraySchemaType(schema: any): string {
  if (Array.isArray(schema.items))
    return `[${schema.items.map(schemaType).join(", ")}]`;
  const itemType = schema.items ? schemaType(schema.items) : "unknown";
  return `Array<${itemType}>`;
}

function objectSchemaType(schema: any): string {
  const properties = Object.entries(schema.properties ?? {}).map(
    ([key, value]) =>
      `${JSON.stringify(key)}${schema.required?.includes(key) ? "" : "?"}: ${schemaType(value)};`,
  );
  const object = `{ ${properties.join(" ")} }`;
  const patterns = Object.values(schema.patternProperties ?? {});
  if (patterns.length)
    return `${object} & Record<string, ${patterns.map(schemaType).join(" | ")}>`;
  if (schema.additionalProperties) {
    const valueType =
      schema.additionalProperties === true
        ? "unknown"
        : schemaType(schema.additionalProperties);
    return `${object} & Record<string, ${valueType}>`;
  }
  return object;
}
