import { emitHandlerFactory, type BrickIR } from "@brickkit/core";

/** An ES module of real JS functions; it never stringifies application callbacks. */
export function emitCompiledApplication(
  ir: BrickIR,
  runtimeImport = "@brickkit/core",
): string {
  return `// Generated by Brick compiler v1. Rebuild after changing application definitions.\nimport { bindCompiledApplication } from ${JSON.stringify(runtimeImport)};\nexport const ir = JSON.parse(${JSON.stringify(JSON.stringify(ir))});\nconst factories = [\n${ir.routes.map(emitHandlerFactory).join(",\n")}\n];\nexport function bind(services) { return bindCompiledApplication(ir, services, factories); }\n`;
}

export { emitHandlerFactory };
export type { BrickIR };
