import type { BrickIR, RouteIR } from "./ir";

/** Emits framework code only. User callbacks remain closures bound separately. */
export function emitHandlerFactory(route: RouteIR): string {
  const name = JSON.stringify(route.action);
  const fields = route.input
    ? "params, body, query, headers, request, set"
    : "headers, request, set";
  const input: string[] = ["let input;"];
  if (route.input) {
    input.push("let coercedQuery = query;");
    if (route.coercions.length) {
      input.push("if (query) {", "coercedQuery = { ...query };");
      for (const [index, coercion] of route.coercions.entries()) {
        const key = JSON.stringify(coercion.key);
        input.push(`const v${index} = query[${key}];`);
        if (coercion.type === "number")
          input.push(
            `if (v${index} !== undefined) { const n${index} = Number(v${index}); if (!Number.isNaN(n${index})) coercedQuery[${key}] = n${index}; }`,
          );
        else
          input.push(
            `if (v${index} === "true" || v${index} === "1") coercedQuery[${key}] = true; else if (v${index} === "false" || v${index} === "0") coercedQuery[${key}] = false;`,
          );
      }
      input.push("}");
    }
    input.push(
      `input = mergeInput(${route.inputPrecedence.map((source) => (source === "query" ? "coercedQuery" : source)).join(", ")});`,
    );
  }
  const asyncStages = route.context || route.authorize;
  const context = route.context
    ? "const extra = await contextHook(ctx); if (extra) Object.assign(ctx, extra);"
    : "";
  const validation = route.input
    ? `validate(inputChecker, input, ${name}, "input");`
    : "";
  const authorization = route.authorize
    ? `if (!await authorize({ ctx, input, user: ctx.user })) deny(${name});`
    : "";
  const output = route.output
    ? `validate(outputChecker, result, ${name}, "output");`
    : "";
  const execute = asyncStages
    ? `const result = await execute({ input, ctx, error: errorBuilder });\n${output}\nreturn result;`
    : `const result = execute({ input, ctx, error: errorBuilder });
if (isThenable(result)) return Promise.resolve(result).then(value => {
  ${route.output ? `validate(outputChecker, value, ${name}, "output");` : ""}
  return value;
}).catch(err => mapError(err, set));
${output}
return result;`;
  return `function bindAction(binding, runtime) {
const { execute, contextHook, authorize, inputChecker, outputChecker, errorBuilder, logger, cachedDb, service } = binding;
const { nextSequence, defaultRequest, emptyServices, mergeInput, validate, deny, mapError, isThenable } = runtime;
return ${asyncStages ? "async " : ""}function brickAction({ ${fields} }) {
const seq = nextSequence();
const traceId = (headers && headers["x-trace-id"]) || "tr_" + seq;
const requestId = (headers && headers["x-request-id"]) || "req_" + seq;
if (set?.headers) { set.headers["x-trace-id"] = traceId; set.headers["x-request-id"] = requestId; }
${input.join("\n")}
const ctx = { request: request instanceof Request ? request : defaultRequest, traceId, requestId,
  db: cachedDb ?? service.getDb(), logger, services: emptyServices, metadata: { headers }, _resolved: true };
try {
${context}
${validation}
${authorization}
${execute}
} catch (err) { return mapError(err, set); }
};
}`;
}

/** An ES module of real JS functions; it never stringifies application callbacks. */
export function emitCompiledApplication(
  ir: BrickIR,
  runtimeImport = "@brickkit/cli/compiler",
): string {
  return `// Generated by Brick compiler v1. Rebuild after changing application definitions.\nimport { bindCompiledApplication } from ${JSON.stringify(runtimeImport)};\nexport const ir = JSON.parse(${JSON.stringify(JSON.stringify(ir))});\nconst factories = [\n${ir.routes.map(emitHandlerFactory).join(",\n")}\n];\nexport function bind(services) { return bindCompiledApplication(ir, services, factories); }\n`;
}
